Improve the Azure documentation
quarkiverse/quarkus-opentelemetry-exporter pull request #153
Opened 2024-03-20 15:10 UTC by jeanbisutti

2024-03-20 15:15 UTC, jeanbisutti commented on docs/modules/ROOT/pages/quarkus-opentelemetry-exporter-azure.adoc
> -`quarkus-opentelemetry` extension already includes the default OTLP exporter. To deactivate that default exporter and only have this Azure extension exporting data, please set the following property
See https://github.com/Azure-Samples/java-native-telemetry/pull/2#discussion_r1532181463

2024-03-20 15:15 UTC, jeanbisutti commented on docs/modules/ROOT/pages/quarkus-opentelemetry-exporter-azure.adoc
>  quarkus.otel.azure.applicationinsights.connection.string=your_connection_string
Is it supposed to work with an environmental variable?QUARKUS_OTEL_AZURE_APPLICATIONINSIGHTS.CONNECTION_STRING?

2024-03-22 10:41 UTC, brunobat requested changes

2024-03-22 10:41 UTC, brunobat commented on docs/modules/ROOT/pages/quarkus-opentelemetry-exporter-azure.adoc
> -quarkus.opentelemetry.tracer.exporter.otlp.enabled=false
It's on by default

2024-03-22 15:34 UTC, brunobat commented on docs/modules/ROOT/pages/quarkus-opentelemetry-exporter-azure.adoc
>  quarkus.opentelemetry.tracer.exporter.azure.enabled=true
To disable it should be 
`quarkus.opentelemetry.tracer.exporter.azure.enabled=false`

2024-03-22 16:08 UTC, brunobat approved these changes
Perfect. Thanks @jeanbisutti

2024-03-22 16:17 UTC, merged